# ITCS 3160-0002, Spring 2024
# Ashton Cox, ashtonmcox@outlook.com
# Andy Pham, apham21@uncc.edu
# Connor Schwab, cschwab3@uncc.edu
# David Saldivar, dsaldiva@uncc.edu
# Jamison Heinrich, jheinri2@uncc.edu
# University of North Carolina at Charlotte
version: '3'

services:
  db:
    build: ./postgresql
    container_name: db
    expose:
      - "5432"
    ports:
      - "5432:5432"
  web:
    build: ./java
    container_name: api
    expose:
      - "8080"
    ports:
      - "8080:8080"
    depends_on:
      - db
